apiVersion: v1
kind: ResourceQuota
metadata:
  name: dso202-quota
  namespace: dso202-assignment-01
spec:
  hard:
    pods: "10"                
    requests.cpu: "1500m"     
    requests.memory: "768Mi"
    limits.cpu: "3"
    limits.memory: "1536Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: dso202-limitrange
  namespace: dso202-assignment-01
spec:
  limits:
    - type: Container
      default:                
        cpu: "500m"
        memory: "256Mi"
      defaultRequest:         
        cpu: "250m"
        memory: "128Mi"
      max:
        cpu: "1"
        memory: "512Mi"
      min:
        cpu: "50m"
        memory: "64Mi"
