apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dso202-assignment-01
  labels:
    course: dso202
type: Opaque
stringData:
  DB_USER: "taskuser"
  DB_PASSWORD: "tshewang123!"          
  POSTGRES_USER: "taskuser"
  POSTGRES_PASSWORD: "tshewang123!"    
